import { createHash } from 'node:crypto'
import { createWriteStream } from 'node:fs'
import { chmod, mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import process from 'node:process'
import { spawn } from 'node:child_process'
import { pipeline } from 'node:stream/promises'
const root = resolve(new URL('..', import.meta.url).pathname)
const enginesRoot = join(root, 'resources/engines')
const manifest = JSON.parse(await readFile(join(enginesRoot, 'manifest.json'), 'utf8'))
const requested = process.env.RELEASE_ARCH || process.env.npm_config_arch || process.arch
const arches = requested === 'both' ? ['arm64', 'x64'] : [requested]
const supported = new Set(manifest.architectures)
const error = (m) => { console.error(`ENGINE ERROR: ${m}`); throw new Error(m) }
const hash = async p => { const h = createHash('sha256'); await pipeline((await import('node:fs')).createReadStream(p), h); return h.digest('hex') }
async function treeHash(dir) { const { readdir } = await import('node:fs/promises'); const h = createHash('sha256'); async function walk(base, rel = '') { for (const n of (await readdir(base, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) { const r = join(rel, n.name); if (n.isDirectory()) await walk(join(base, n.name), r); else { h.update(r); h.update(await readFile(join(base, n.name))) } } } await walk(dir); return h.digest('hex') }
const run = (file, args) => new Promise((ok, bad) => { const p = spawn(file, args, { stdio: ['ignore', 'pipe', 'pipe'] }); let out = ''; let e = ''; p.stdout.on('data', d => { out += d }); p.stderr.on('data', d => { e += d }); p.on('error', bad); p.on('close', c => c === 0 ? ok(`${out}${e}`) : bad(new Error(`${file} exited ${c}: ${e.slice(-300)}`))) })
function assertVersion(output, version, name) { if (!output.includes(version)) error(`${name} version output does not contain pinned version ${version}`) }
async function providerContract(target) { const port = 41000 + Math.floor(Math.random() * 1000); const child = spawn(target, ['server', '--host', '127.0.0.1', '--port', String(port)], { stdio: 'ignore' }); try { for (let i = 0; i < 30; i++) { try { const r = await fetch(`http://127.0.0.1:${port}/ping`); if (r.status >= 200 && r.status < 500) return } catch {} await new Promise(r => setTimeout(r, 100)) } throw new Error('provider contract failed: /ping did not answer') } finally { child.kill('SIGTERM') } }
function validate() { if (process.platform !== 'darwin') error(`unsupported host ${process.platform}`); if (arches.some(a => !supported.has(a))) error(`unsupported architecture ${arches.join(',')}`) }
function pinned(url, version) { return /^https:\/\/(github\.com|evermeet\.cx|ffmpeg\.martin-riedl\.de)\//.test(url) && !/(latest|main|master)/.test(url) && url.includes(version.replace(/^v/, '')) }
async function download(url, expected, path) { const r = await fetch(url, { redirect: 'follow' }); if (!r.ok || !r.body) throw new Error(`download failed HTTP ${r.status}`); await pipeline(r.body, createWriteStream(path)); if (await hash(path) !== expected) throw new Error('archive checksum mismatch') }
async function extract(item, archive, dest, name) { const temp = join(dest, `.incoming-${name}`); await rm(temp, { recursive: true, force: true }); await mkdir(temp, { recursive: true }); await run('unzip', ['-q', '-o', archive, '-d', temp]); const source = join(temp, item.member); await stat(source); const target = join(dest, name); await rm(target, { force: true }); if (name === 'yt-dlp') { const sidecar = join(temp, '_internal'); await stat(sidecar); await rm(join(dest, '_internal'), { recursive: true, force: true }); await rename(sidecar, join(dest, '_internal')) } await rename(source, target); await rm(temp, { recursive: true, force: true }); return target }
async function machArch(p) { return new Promise((ok, bad) => { const q = spawn('file', ['-b', p], { stdio: ['ignore', 'pipe', 'pipe'] }); let s = ''; q.stdout.on('data', d => { s += d }); q.on('error', bad); q.on('close', c => c ? bad(new Error('file failed')) : ok(s)) }) }
function archOK(text, arch) { return arch === 'arm64' ? /arm64/.test(text) : /x86_64/.test(text) }
async function oneArch(arch, mode, metadata, sums) {
  const dir = join(enginesRoot, `darwin-${arch}`); const po = join(enginesRoot, 'po-token', `darwin-${arch}`); await mkdir(dir, { recursive: true }); await mkdir(po, { recursive: true }); const temp = join(enginesRoot, `.download-${arch}`); await rm(temp, { recursive: true, force: true }); await mkdir(temp)
  try {
    for (const [name, item] of Object.entries(manifest.engines)) {
      const target = join(name === 'bgutil-provider' ? po : dir, name); const source = item.archives ? item.archives[arch] : item
      if (!pinned(source.url || source.archive, item.version)) error(`un-pinned ${name}`)
      if (mode === 'fetch') { const a = join(temp, name); if (name === 'yt-dlp') { await rm(target, { force: true }); await rm(join(dir, '_internal'), { recursive: true, force: true }) } await download(source.url || source.archive, source.sha256 || source.sha256, a); if (item.kind === 'raw') await rename(a, target); else await extract(item, a, dir, name); await chmod(target, 0o755) }
      await stat(target); if (!(await machArch(target)).includes(arch === 'arm64' ? 'arm64' : 'x86_64')) error(`wrong architecture for ${target}`); assertVersion(await run(target, item.versionArgs), item.version, name); if (name === 'bgutil-provider') await providerContract(target)
      const installed = await hash(target); sums.push(`${installed}  resources/engines/${name === 'bgutil-provider' ? `po-token/darwin-${arch}/bgutil-provider` : `darwin-${arch}/${name}`}`); metadata.architectures[`darwin-${arch}`][name] = { version: item.version, sourceUrl: source.url || source.archive, archiveSha256: source.sha256 || source.sha256, installedSha256: installed, architecture: arch, verifiedAt: new Date().toISOString(), buildIdentity: process.env.BUILD_ID || 'local' }
      if (name === 'yt-dlp') { const sidecar = join(dir, '_internal'); await stat(join(sidecar, 'Python')); const sidecarHash = await treeHash(sidecar); sums.push(`${sidecarHash}  resources/engines/darwin-${arch}/_internal`); metadata.architectures[`darwin-${arch}`]['yt-dlp-sidecar'] = { installedSha256: sidecarHash, path: `resources/engines/darwin-${arch}/_internal`, requiredFile: 'Python', architecture: arch, buildIdentity: process.env.BUILD_ID || 'local' } }
    }
    const plugin = manifest.engines['bgutil-provider'].plugin; const pluginDir = join(po, 'yt_dlp_plugins'); const pluginArchive = join(temp, 'bgutil-plugin.zip')
    if (!pinned(plugin.archive, plugin.version)) error('un-pinned bgutil plugin')
    if (mode === 'fetch') { await download(plugin.archive, plugin.sha256, pluginArchive); await mkdir(pluginDir, { recursive: true }); await run('unzip', ['-q', '-o', pluginArchive, '-d', po]) }
    await stat(pluginDir); const pluginHash = await treeHash(pluginDir); sums.push(`${pluginHash}  resources/engines/po-token/darwin-${arch}/yt_dlp_plugins`); metadata.architectures[`darwin-${arch}`]['bgutil-plugin'] = { version: plugin.version, sourceUrl: plugin.archive, archiveSha256: plugin.sha256, installedSha256: pluginHash, installPath: `resources/engines/po-token/darwin-${arch}/yt_dlp_plugins`, architecture: arch, buildIdentity: process.env.BUILD_ID || 'local' }
  } finally { await rm(temp, { recursive: true, force: true }) }
}
async function main() { validate(); const mode = process.argv[2] === 'verify' ? 'verify' : 'fetch'; let metadata = { schemaVersion: 1, generatedAt: new Date().toISOString(), buildIdentity: process.env.BUILD_ID || 'local', architectures: {} }; const sums = []
  if (mode === 'fetch') { try { metadata = JSON.parse(await readFile(join(enginesRoot, 'metadata.json'), 'utf8')); } catch {} metadata.generatedAt = new Date().toISOString(); metadata.buildIdentity = process.env.BUILD_ID || metadata.buildIdentity || 'local' }
  for (const a of arches) metadata.architectures[`darwin-${a}`] = {}
  if (mode === 'fetch') { try { const prior = await readFile(join(enginesRoot, 'SHA256SUMS'), 'utf8'); for (const line of prior.split(/\r?\n/).filter(Boolean)) if (!arches.some(a => line.includes(`darwin-${a}/`))) sums.push(line) } catch {} }
  for (const a of arches) await oneArch(a, mode, metadata, sums)
  if (mode === 'fetch') { await writeFile(join(enginesRoot, 'SHA256SUMS'), `${sums.join('\n')}\n`); await writeFile(join(enginesRoot, 'metadata.json'), `${JSON.stringify(metadata, null, 2)}\n`) }
  else { const saved = JSON.parse(await readFile(join(enginesRoot, 'metadata.json'), 'utf8')); const sumsText = await readFile(join(enginesRoot, 'SHA256SUMS'), 'utf8'); for (const a of arches) { const archMeta = saved.architectures?.[`darwin-${a}`]; if (!archMeta) error(`missing metadata entry for darwin-${a}`); for (const n of Object.keys(manifest.engines)) { const p = join(enginesRoot, n === 'bgutil-provider' ? `po-token/darwin-${a}/${n}` : `darwin-${a}/${n}`); const entry = archMeta[n]; if (!entry?.installedSha256) error(`missing metadata checksum for ${p}`); const got = await hash(p); const rel = `resources/engines/${n === 'bgutil-provider' ? `po-token/darwin-${a}/${n}` : `darwin-${a}/${n}`}`; if (got !== entry.installedSha256) error(`metadata checksum mismatch ${p}`); if (!sumsText.split(/\r?\n/).includes(`${got}  ${rel}`)) error(`missing SHA256SUMS entry for ${rel}`); assertVersion(await run(p, manifest.engines[n].versionArgs), manifest.engines[n].version, n); if (n === 'bgutil-provider') await providerContract(p) } const sidecar = join(enginesRoot, `darwin-${a}/_internal`); const se = archMeta['yt-dlp-sidecar']; if (!se?.installedSha256) error(`missing yt-dlp sidecar metadata for ${sidecar}`); await stat(join(sidecar, 'Python')); const sh = await treeHash(sidecar); if (sh !== se.installedSha256 || !sumsText.split(/\r?\n/).includes(`${sh}  resources/engines/darwin-${a}/_internal`)) error(`missing or invalid yt-dlp sidecar ${sidecar}`); const pp = join(enginesRoot, `po-token/darwin-${a}/yt_dlp_plugins`); const pe = archMeta['bgutil-plugin']; if (!pe?.installedSha256) error(`missing metadata checksum for provider plugin ${pp}`); await stat(pp); const ph = await treeHash(pp); if (ph !== pe.installedSha256) error(`provider plugin metadata checksum mismatch ${pp}`); if (!sumsText.split(/\r?\n/).includes(`${ph}  resources/engines/po-token/darwin-${a}/yt_dlp_plugins`)) error(`missing SHA256SUMS entry for provider plugin ${pp}`) } }
}
main().catch(e => { console.error(`ENGINE ERROR: ${e.message}`); process.exitCode = 1 })
