import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { filterValidCookieRecords, isAllowedOrigin, hasValidCapability, isAuthorizedExtensionRequest, isAllowedCookieDomain, validateCookieRecord, validateDownloadPayload } from '../src/main/securityValidation'
import { redact } from '../src/main/worklog'
import { getUnpackedChromeExtensionId } from '../src/main/extensionIdentity'
assert.equal(isAllowedOrigin(undefined), false)
assert.equal(isAllowedOrigin('chrome-extension://not-an-id'), false)
const capability = 'a'.repeat(64)
assert.equal(hasValidCapability(undefined, capability), false)
assert.equal(hasValidCapability('b'.repeat(64), capability), false)
assert.equal(hasValidCapability(capability, capability), true)
assert.equal(isAllowedOrigin('https://evil.example'), false)
const extensionId = 'a'.repeat(32)
assert.equal(getUnpackedChromeExtensionId('/Users/mingjie/Documents/github/personal-projects/v-download/extension'), 'ggolokdmilobpagmcbebkdpmkbnjhmgb')
assert.equal(isAllowedOrigin(`chrome-extension://${extensionId}`), false)
assert.equal(isAllowedOrigin(`chrome-extension://${extensionId}`, { allowUnpinned: true }), true)
assert.equal(isAllowedOrigin(`chrome-extension://${extensionId}`, { allowedExtensionIds: new Set([extensionId]) }), true)
assert.equal(isAllowedOrigin(`chrome-extension://${'b'.repeat(32)}`, { allowedExtensionIds: new Set([extensionId]) }), false)
assert.equal(isAllowedOrigin(`chrome-extension://${'b'.repeat(32)}`, { allowedExtensionIds: new Set([extensionId]), allowUnpinned: true }), true)
assert.equal(isAuthorizedExtensionRequest(`chrome-extension://${extensionId}`, undefined, capability, { allowUnpinned: true }), true)
assert.equal(isAuthorizedExtensionRequest(`chrome-extension://${extensionId}`, undefined, capability, { allowedExtensionIds: new Set([extensionId]) }), false)
assert.equal(isAuthorizedExtensionRequest(undefined, capability, capability, { allowedExtensionIds: new Set([extensionId]) }), false)
assert.equal(isAuthorizedExtensionRequest(`chrome-extension://${extensionId}`, undefined, capability, { allowedExtensionIds: new Set([extensionId]) }), false)
assert.equal(isAuthorizedExtensionRequest('https://evil.example', undefined, capability, { allowUnpinned: true }), false)
assert.equal(isAllowedCookieDomain('.twitter.com'), true)
assert.equal(isAllowedCookieDomain('.iesdouyin.com'), true)
assert.equal(isAllowedCookieDomain('.evil.example'), false)
assert.equal(validateCookieRecord({ domain: '.instagram.com', name: 'sid', value: 'x', path: '/', secure: true, httpOnly: true, session: true }), true)
assert.equal(validateCookieRecord({ domain: '.instagram.com', name: 'sid', value: 'x', path: 'relative', secure: true, httpOnly: true }), false)
assert.equal(validateCookieRecord({ domain: '.instagram.com', name: 'sid', value: 'x', path: '/', secure: 'yes', httpOnly: true }), false)
assert.equal(validateCookieRecord({ domain: '.instagram.com', name: 'sid\n', value: 'x', path: '/', secure: true, httpOnly: true }), false)
assert.equal(validateCookieRecord({ domain: '.instagram.com', name: 'sid', value: 'x\tINJECT', path: '/', secure: true, httpOnly: true }), false)
assert.equal(validateCookieRecord({ domain: '.instagram.com', name: 'sid', value: 'x', path: '/\nSet-Cookie: evil=1', secure: true, httpOnly: true }), false)
const filteredCookies = filterValidCookieRecords([
  { domain: '.douyin.com', name: 'sid', value: 'valid', path: '/', secure: true, httpOnly: true },
  { domain: 'www.douyin.com', name: '', value: 'legacy-empty-name', path: '/', secure: false, httpOnly: false },
  { domain: '.evil.example', name: 'sid', value: 'blocked', path: '/', secure: true, httpOnly: true },
])
assert.equal(filteredCookies.valid.length, 1)
assert.equal(filteredCookies.skipped, 2)
assert.equal(validateDownloadPayload({ url: 'https://example.com/v.mp4', type: 'mp4', title: 'ok', headers: { Referer: 'https://example.com' } }).ok, true)
assert.equal(validateDownloadPayload({ url: 'https://www.douyin.com/video/123456789', quality: '720', autoStart: true }).ok, true)
assert.equal(validateDownloadPayload({ url: 'https://www.douyin.com/video/123456789', quality: '720p' }).ok, false)
assert.equal(validateDownloadPayload({ url: 'https://www.douyin.com/video/123456789', autoStart: 'true' }).ok, false)
assert.equal(validateDownloadPayload({ url: 'javascript:alert(1)' }).ok, false)
assert.equal(validateDownloadPayload({ url: 'https://example.com', type: 'exe' }).ok, false)
assert.equal(validateDownloadPayload({ url: 'https://example.com/audio.wav', type: 'wav' }).ok, true)
assert.equal(validateDownloadPayload({ url: 'https://example.com/audio.flac', type: 'flac' }).ok, true)
assert.equal(validateDownloadPayload({ url: 'https://example.com', headers: { 'Bad Header': 'x' } }).ok, false)
assert.equal(JSON.stringify({ error: 'Invalid download request' }).includes('sig='), false)
const redacted = String(redact('https://host/video.mp4?sig=SECRET&token=SECRET2 Authorization: BearerSECRET Cookie: sid=COOKIE X-VDownload-Capability: CAP /Users/alice/private.txt'))
assert.ok(!redacted.includes('SECRET') && !redacted.includes('COOKIE') && !redacted.includes('CAP') && !redacted.includes('/Users/alice'))
const extraRedacted = JSON.stringify(redact({ nested: { url: 'https://host/video.mp4?sig=SECRET', authorization: 'Bearer SECRET', cookie: 'sid=COOKIE', capability: 'CAP', capabilityToken: 'CAPTOKEN', capabilitySecret: 'CAPSECRET', pairingSecret: 'PAIRSECRET', path: '/Users/alice/private.txt' } }))
assert.ok(!extraRedacted.includes('SECRET') && !extraRedacted.includes('COOKIE') && !extraRedacted.includes('CAP') && !extraRedacted.includes('/Users/alice'))
const worklogErrorExtraLike = JSON.stringify(redact({ extra: { capabilityToken: 'CAPTOKEN', authorization: 'Bearer SECRET', cookie: 'sid=COOKIE', path: '/Users/alice/private.txt' } }))
assert.ok(!worklogErrorExtraLike.includes('CAPTOKEN') && !worklogErrorExtraLike.includes('SECRET') && !worklogErrorExtraLike.includes('COOKIE') && !worklogErrorExtraLike.includes('/Users/alice'))
const background = readFileSync(new URL('../extension/background.js', import.meta.url), 'utf8')
assert.doesNotMatch(background, /VDL_SERVER_URL/)
assert.doesNotMatch(background, /\/api\/cookies/)
assert.match(background, /postAppJson\('\/cookies', allCookies\)/)
assert.doesNotMatch(background, /onInstalled\.addListener\(\(\) => \{\s*syncCookies/s)
assert.doesNotMatch(background, /onStartup\.addListener\(\(\) => \{\s*syncCookies/s)
console.log('security validators: origin, pairing boundary, cookie records, download payloads, and redaction fixtures passed')
